### ISSUE TITLE
make error Please add -D_FILE_OFFSET_BITS=64

### ISSUE THREAD

**Issue by k3dar** [k3dar/rdiff-backup-fs#6]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
I am trying to compile with 64 bit Ubuntu 10.10 (32 bit was ok). The error I 
get is:

make
make  all-recursive
make[1]: Entering directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0'
Making all in layout
make[2]: Entering directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0/layout'
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O3  -MT all.o -MD -MP -MF .deps/all.Tpo 
-c -o all.o all.c
In file included from /usr/include/fuse/fuse.h:26,
                 from /usr/include/fuse.h:9,
                 from ../externs.h:6,
                 from all.h:5,
                 from all.c:1:
/usr/include/fuse/fuse_common.h:32: error: #error Please add 
-D_FILE_OFFSET_BITS=64 to your compile flags!
make[2]: *** [all.o] Error 1
make[2]: Leaving directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0/layout'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0'
make: *** [all] Error 2

```

Original issue reported on code.google.com by `mek...@gmail.com` on 7 May 2011 at 6:14

_Copied from original issue: rbrito/rdiff-backup-fs#6_

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
Have you pkg-config and libfuse-dev installed?
```

Original comment by `grusz...@gmail.com` on 8 May 2011 at 7:30
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
Yes, I eventually got it to compile by modifying the configure file - adding 
the -D_FILE_OFFSET_BITS=64

In fact I found this problem was reported previously as issue 11 in the archfs 
issues tracker.



```

Original comment by `mek...@gmail.com` on 11 May 2011 at 7:33

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
You should not need to modify configure file by adding this flag. pkg-config 
should does it for you. You should be able to do this in your terminal:

$ pkg-config --cflags fuse
-D_FILE_OFFSET_BITS=64 -I/usr/include/fuse

The same is called in configure script.
```

Original comment by `grusz...@gmail.com` on 14 May 2011 at 4:32

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

Original comment by `grusz...@gmail.com` on 14 May 2011 at 4:33
- Changed state: **WontFix**

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
Installing pkg-config seemed to fix the issue for me
```

Original comment by `dent...@gmail.com` on 22 Feb 2014 at 3:19

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
Will the FUSE 2.9.3 work well on Ubuntu 14.04 ( 32 bit machine)
```

Original comment by `sk4...@nyu.edu` on 17 Mar 2015 at 3:46

**Comment by k3dar** [comment]
_From @GoogleCodeExporter on July 5, 2015 0:23_

```
How to install pkg-config 

```

Original comment by `sk4...@nyu.edu` on 17 Mar 2015 at 10:42
